Add absences
Damego/ETIS-mobile pull request #104
Opened 2023-09-11 07:09 UTC by esperor

![image](https://github.com/Damego/ETIS-mobile/assets/49198951/77d6ed15-edad-449c-8de9-d10287cad7f5)
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/fba293a6-c696-4693-80ca-6166486d1f57)

2023-09-12 09:12 UTC, Damego requested changes
Некоторые моменты я упустил, позже сам сделаю как нужно

2023-09-12 09:12 UTC, Damego commented on src/utils/http.ts
> +    if (typeof(period) !== 'undefined') {
```suggestion
    if (period) {
```

2023-09-12 09:12 UTC, Damego commented on src/utils/http.ts
> +    let object: PayloadWithString = { returnResponse: false, params: {} };
А зачем надо было выносить всё это в объект?

2023-09-12 12:59 UTC, esperor commented on src/parser/absences.ts
> +  let overallMissed: string = $('div.span9', html).text().split(' ').at(-1);
Не фанат регулярок, не умею их использовать
html как контекст чтобы не делать дополнительный load других элементов, div.span9 находится практически в корне

2023-09-12 13:02 UTC, Damego commented on src/parser/absences.ts
> +  let overallMissed: string = $('div.span9', html).text().split(' ').at(-1);
У тебя `$` содержит весь html страницы

2023-09-12 13:06 UTC, esperor commented on src/utils/http.ts
> +    let object: PayloadWithString = { returnResponse: false, params: {} };
чтобы не дублировать код: если период дан, просто добавим его как параметр к существующему запросу, а не будет писать запрос заново

2023-09-12 13:08 UTC, esperor commented on src/utils/http.ts
> +    let object: PayloadWithString = { returnResponse: false, params: {} };
чтобы не дублировать код: если период дан, просто добавим его как параметр к существующему запросу, а не будет писать запрос заново

2023-09-12 13:17 UTC, esperor commented on src/parser/absences.ts
> +        fields[i - 1] = td.eq(i).html().trim().split('<br>');
`<br>` делит даты не на тексты, а на блоки `<font colot=red/green>22.09.2023</font>` (для примера), которые еще потом нужно пропарсить: `dates.map(parseDate)`

2023-09-12 13:19 UTC, esperor commented on src/parser/absences.ts
> +  let overallMissed: string = $('div.span9', html).text().split(' ').at(-1);
`$('tr', html)` - твой код, тут то же указан html
честно говоря, не слишком думал про это, делал по существующему примеру

2023-09-12 13:26 UTC, esperor commented on src/screens/absences/AbsencesStyles.ts
Исправлено

2023-09-12 13:26 UTC, esperor commented on src/cache/smartCache.ts
> +  async getAbsences(trimester: number) {
Ошибка, забыл сменить на период
Исправлено

2023-09-12 13:40 UTC, esperor commented on src/screens/absences/AbsencesStyles.ts
Исправлено

2023-09-12 13:48 UTC, Damego commented on src/parser/absences.ts
> +  let overallMissed: string = $('div.span9', html).text().split(' ').at(-1);
Не мой код, а друга, который уже не участвует в разработке

2023-09-17 15:12 UTC, ijo42 commented on src/models/dropdown.ts
откуда речь про дропдавн, если в итоге используются кликейбл текст

2023-09-17 15:19 UTC, esperor commented on src/models/dropdown.ts
в какой-то момент пробовал использовать dropdown, но в итоге не понравился дизайн с ним и переключился на clickableText. Пока пробовал dropdown, заметил, что он неудобен в силу отсутствия понятного интерфейса, решил пофиксить. В целом можно это обратить, если лишнее

2023-09-17 15:22 UTC, esperor commented on src/screens/absences/index.js
Следовал примеру из других экранов (teachers, signs, timeTable)

2023-09-18 03:26 UTC, Damego commented on src/models/dropdown.ts
Вернул dropdown

2023-09-18 03:36 UTC, Damego approved these changes

2023-09-18 03:36 UTC, merged