feat&fix: signs (add modal)
Damego/ETIS-mobile pull request #108
Opened 2023-09-17 09:30 UTC by esperor

В первую очередь пр добавляет модальное окно с подробностями для КТ:  
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/158aedb3-aff5-4806-8b31-6987a4333669)
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/83ac668b-dfed-48d4-954d-24e06b1ead3c)
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/cca9cbe6-4bef-4c2f-8205-a2d91afc23d6)
Также фиксит (?) #107 путем удаления `if (!endDate) return;`
Также в некоторые компоненты были добавлены дополнительные аргументы style: `Button`, `CardHeaderIn`, `CardHeaderOut`

2023-09-17 15:06 UTC, ijo42 commented on src/screens/signs/SignModal.tsx
> +    <Modal transparent onRequestClose={closeModal}>
можно сделать и будет проще через Popout (см. CertificateTable.tsx)

2023-09-17 15:06 UTC, ijo42 commented on src/parser/sessionMarks.ts
> +      //if (!endDate) return;
лучше вынести в другой ПР
по поводу кода - если считаешь, что он не нужен - удаляй, не комментируй

2023-09-17 15:08 UTC, ijo42 commented
По поводу коммит-хистори, очень много коммитов, большинство из которых ненужно, по крайней мере стоит вынести изменения в sessionMark.ts в отдельный коммит, а остальное засквешит, иначе в мердж-ветке потеряется суть (из названий коммитов не видно о чем речь)

2023-09-17 15:59 UTC, esperor commented on src/screens/signs/SignModal.tsx
> +    <Modal transparent onRequestClose={closeModal}>
Попробую поменять на него

2023-09-17 16:00 UTC, esperor commented on src/parser/sessionMarks.ts
> +      //if (!endDate) return;
Выведу в другой пр это тогда
Но это был скорее вопрос, не комментарий
Я всего не знаю и не могу увидеть всю картину и все edge-кейсы

2023-09-18 03:43 UTC, Damego commented
<img width="221" alt="image" src="https://github.com/Damego/ETIS-mobile/assets/25762802/15ba187d-6094-4d1d-93a5-4cc6d49093aa">

Поле с датой и преподавателем нет смысла показывать, если нет выставленных баллов

2023-09-18 04:57 UTC, Damego requested changes

2023-09-18 04:57 UTC, Damego commented on src/screens/signs/SignModal.tsx
> +    return 'КТ ' + number + ': ' + theme;
```suggestion
  const getCheckpointTitle = (theme: string, number: number) => {
    return `КТ ${number}: ${theme}`;
```

2023-09-18 04:57 UTC, Damego commented on src/screens/signs/SignModal.tsx
> +    return 'КТ ' + number + ': ' + theme;
Я сначала подумал, какой point title ты там проверяешь.

2023-09-18 04:57 UTC, Damego commented on src/screens/signs/SignModal.tsx
> +                topText={checkPointTitle(checkPoint.theme, index + 1)}
```suggestion
                topText={getCheckpointTitle(checkPoint.theme, index + 1)}
```

2023-09-18 04:57 UTC, Damego commented on src/screens/signs/SignModal.tsx
> +                <TextRow        text={'Преподаватель: ' + checkPoint.teacher} />
Не вижу смысла в `DoubleTextRow`. Либо ты только его используешь, либо только `TextRow`, иначе получается каша. 
Объедини строки не конкатенацией

2023-09-18 04:57 UTC, Damego commented on src/screens/signs/styles.ts
Странное решение вынести стили в отдельный файл, хотя такое в проекте нигде не встречается (исключение только более общие стили, которые применяются по всему проекту).
Никто же не мешает создать свои стили в каждом файле, а не выносить всё

2023-09-18 04:57 UTC, Damego commented on src/components/Button.tsx
К чему тут изменения, если ты кнопку нигде не используешь?

2023-09-19 19:54 UTC, esperor commented on src/screens/signs/SignModal.tsx
> +    <Modal transparent onRequestClose={closeModal}>
Если я правильно понял, то речь была про Popover
Опытным путем выяснено, что смена на него требует переписывания всего виджета
Не вижу таких преимуществ от его использования, чтобы это было оправдано

2023-09-19 20:12 UTC, esperor commented on src/components/Button.tsx
Исправлено

2023-09-19 20:16 UTC, esperor commented on src/screens/signs/styles.ts
Исправлено

2023-09-19 20:16 UTC, esperor commented on src/screens/signs/SignModal.tsx
> +                <TextRow        text={'Преподаватель: ' + checkPoint.teacher} />
Исправлено

2023-09-19 20:18 UTC, esperor commented
> По поводу коммит-хистори, очень много коммитов, большинство из которых ненужно, по крайней мере стоит вынести изменения в sessionMark.ts в отдельный коммит, а остальное засквешит, иначе в мердж-ветке потеряется суть (из названий коммитов не видно о чем речь)

@ijo42 sessionMark.ts вывел в отдельный пр; squash до конце не понял, но по идее при принятии пр есть опция весь пр как один коммит включить, так что проблемой не будет

2023-09-19 20:39 UTC, esperor commented
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/2bd9e4fb-4a02-48da-8872-25517274bea9)
Поменял положение "Подробнее..."

2023-09-21 17:01 UTC, esperor commented
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/33de08c2-3854-41fd-84e7-024f38904f09)
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/700ac64d-bd32-4743-9aea-d9aa7f92427c)
Изменил способ показа деталей с модала на отдельный экран, слегка изменил шапку экрана, сделал рефактор стилей

2023-09-21 17:29 UTC, Damego reviewed
<img width="263" alt="image" src="https://github.com/Damego/ETIS-mobile/assets/25762802/38930a42-c237-4072-ba9a-a39ba9a96005">

Может я не так объяснил. Я имел ввиду, что у тебя вид текста после двоеточия отличается для баллов и остального текста. Лучше, чтобы это было в едином стиле, т.е. баллы показывать сразу после двоеточия, а не на другом конце.
Также сделай отступ слева меньше. А то он слишком большой. Пусть будет 2%.
Оценку и текущий балл тоже нет смысла показывать, если они не выставлены.
Попробуй шрифт сделать чуть больше.
Также думаю, что можно мысленно разделить отступом текст на 2 группы:
1) Баллы, препод, дата
2) вся остальная фигня (она в принципе не особо нужна)

2023-09-21 17:29 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +    marginVertical: 15,
```suggestion
    marginBottom: '2%',
```

2023-09-21 17:29 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +export default function SignsDetails({ route, navigation }) {
```suggestion
export default function SignsDetails({ route }) {
```

2023-09-21 17:29 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +      <Text style={useGlobalStyles().textColor}>{second}</Text>
вынеси useGlobalStyles в константу

2023-09-21 17:29 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +        <Text style={[globalStyles.textColor, fontSize.large, { maxWidth: '80%' }]}>
```suggestion
        <Text style={[globalStyles.textColor, fontSize.large, { flex: 1 }]}>
```

2023-09-21 17:29 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +          style={{ alignSelf: 'stretch' }}
```suggestion
```

2023-09-21 17:46 UTC, esperor commented on src/screens/signs/SignsDetails.tsx
> +        <Text style={[globalStyles.textColor, fontSize.large, { maxWidth: '80%' }]}>
`maxWidth` здесь чтобы ограничить название предмета, чтобы было пространство между названием и баллами
не понимаю, зачем менять на `flex: 1`, он не сделает так

2023-09-21 17:52 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
> +        <Text style={[globalStyles.textColor, fontSize.large, { maxWidth: '80%' }]}>
Не люблю ставить ширину/высоту. Если хочешь добавить отступ, то используй margin или padding или можешь добавить gap родительскому компоненту

2023-09-21 18:02 UTC, esperor commented on src/screens/signs/SignsDetails.tsx
> +          style={{ alignSelf: 'stretch' }}
Удалил

2023-09-21 18:02 UTC, esperor commented on src/screens/signs/SignsDetails.tsx
> +      <Text style={useGlobalStyles().textColor}>{second}</Text>
Сделано

2023-09-21 18:04 UTC, esperor commented
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/83d0bd56-3a97-4d0e-8c5f-cebc04a82665)

2023-09-21 18:07 UTC, esperor commented
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/32c8ee23-cca4-4d9a-927f-8b74490b2040)
Поставил размер текста 15: между small (default) и medium (заголовок карточки)

2023-09-24 15:44 UTC, Damego approved these changes

2023-09-24 15:45 UTC, merged