feat: show teacher's name in Lesson
Damego/ETIS-mobile pull request #125
Opened 2023-10-08 16:46 UTC by esperor

Downloads the teachers info in the timeTable (only once, doesn't reload it on week change)
Closes https://github.com/users/Damego/projects/1/views/3?pane=issue&itemId=35601560

2023-10-09 17:06 UTC, Damego requested changes
Также переименуй все `teachers_data` в `teachersData`. У нас тут не питон

2023-10-09 17:06 UTC, Damego commented on src/parser/timeTable.ts
> +            teacherId: Number(teacherId),
Думаю, что можно оставить строкой

2023-10-09 17:06 UTC, Damego commented on src/screens/timeTable/Pair.tsx
> +  teachers_data.map((value: [string, ITeacher[]], index: number) => {
```suggestion
  teachers_data.forEach((value: [string, ITeacher[]], index: number) => {
```

2023-10-09 17:13 UTC, esperor commented on src/screens/timeTable/Pair.tsx
> +  teachers_data.map((value: [string, ITeacher[]], index: number) => {
Исправлено

2023-10-09 17:13 UTC, esperor commented on src/parser/timeTable.ts
> +            teacherId: Number(teacherId),
Исправлено

2023-10-09 17:14 UTC, esperor commented on src/parser/timeTable.ts
> +            teacherId: Number(teacherId),
Что оставить строкой? teacherId?

2023-10-09 17:20 UTC, Damego commented on src/parser/timeTable.ts
> +            teacherId: Number(teacherId),
да

2023-10-09 17:22 UTC, Damego reviewed
Я думал, ты заметишь при рефакторинге, а ты не заметил(

`teachers_isLoading` -> `teachersLoading` или `teachersAreLoading`
![image](https://github.com/Damego/ETIS-mobile/assets/25762802/912135c5-8ba8-443f-b125-7f48b00eb6a2)

2023-10-09 17:46 UTC, esperor commented
![image](https://github.com/Damego/ETIS-mobile/assets/49198951/1294dcf0-1eb1-49f3-b577-9d52dac08e65)

2023-10-09 17:46 UTC, esperor commented on src/parser/timeTable.ts
> +            teacherId: Number(teacherId),
Исправлено

2023-10-10 15:43 UTC, Damego approved these changes

2023-10-10 15:44 UTC, merged