Fix edge case for teacher not assigned or regex not passed
Damego/ETIS-mobile pull request #129
Opened 2023-10-17 11:50 UTC by esperor

Also added reportReturn function into sentry.ts for convenience

2023-10-18 08:39 UTC, Damego requested changes

2023-10-18 08:39 UTC, Damego commented on src/parser/timeTable.ts
> +  if (!teacherAnchor) return '-1';
1. cheerio не возвращает `null` или `undefined`, если тег не был найден. Проверь через `!teacherAnchor.length`
2. Зачем возвращать `-1`, если можно вернуть `null` или `undefined`?

2023-10-18 08:39 UTC, Damego commented on src/parser/timeTable.ts
> +  if (!teacherId) return '-1';
Зачем возвращать `-1`, если можно вернуть `null` или `undefined`?

2023-10-18 08:39 UTC, Damego commented on src/utils/sentry.ts
> +  return returnValue;
Исходя из вышесказанного это нам не нужно

2023-10-18 09:04 UTC, esperor commented
Разъебал по фактам

2023-10-21 17:36 UTC, Damego approved these changes

2023-10-21 17:37 UTC, merged