feat: show date of last point change
Damego/ETIS-mobile pull request #143
Opened 2024-02-05 13:12 UTC by esperor

Даты изменений оценки подгружаются по клику в виде xhr (~30 ms на реквест)
При открытии SignsDetails будем подгружать даты для КТшек если в КТ установлен teacher
Пока происходит загрузка, оценка будет показываться как "Загрузка..."
На практике надпись "Загрузка..." висит примерно 0.5-0.7 сек (на глаз)

2024-02-22 05:33 UTC, Damego requested changes
И добавь кэширование

2024-02-22 05:33 UTC, Damego commented on src/parser/pointUpdates.ts
> +    return executeRegex(lastPointDateRegex, xhr)[0];
`xhr`? Чем `data` не устраивает?
Почему бы не вернуть `null`, вместо строки?
А запрос возвращает перенос строки, что равно 1 символу

2024-02-22 05:33 UTC, Damego commented on src/parser/sessionPoints.ts
> +      const updatesUrl = '/' + tds.eq(3).attr('data-url');
Спарси айдишники через `URL`, и запиши в какой-нибудь объект

2024-02-22 05:33 UTC, Damego commented on src/screens/signs/SignsDetails.tsx
>              <Row first={'Вид работы:'} second={checkPoint.typeWork} />
Компонент стал слишком большой. Вынеси его

2024-02-22 05:33 UTC, Damego commented on src/utils/http.ts
> +  getPointUpdates(url: string): Promise<Response<string>> {
Из полученных айдишников делай запрос

2024-02-22 11:23 UTC, esperor commented on src/parser/sessionPoints.ts
> +      const updatesUrl = '/' + tds.eq(3).attr('data-url');
Зачем?

2024-02-28 15:51 UTC, Damego commented
Обнови ветку с development

2024-03-02 03:46 UTC, Damego approved these changes

2024-03-03 06:51 UTC, merged